version: '3.1'

services:
  sarbacane:
    build: .
    restart: always
    container_name: sarbacane
    ports:
      - 8080:8080
      - 8000:8000
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always
